version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - npm i --save
            - echo "we will run some tests"
            - grep -Fq "CloudMentorPro" index.html
    post_build:
        commands:
            - echo "we are in the post build phase"

artifacts:
    files:
        - '**/*'
